### ISSUE TITLE
HTTPS Proble

### ISSUE THREAD

**Issue by delllaptop9100** [jvansteirteghem/apjp#2]
Hi,
I,m using APJP since 2009. recently I can't surf some website that is on https protocol, like:
https://www.instagram.com/
https://nl.gonewvm.com/
I tested in Chrome, Firefox (latest version). Im using Windows 7 and also installed latest java ((JRE) v8 Update).
Server side is CentOS Linux 5.11 with Kloxo panel.
Any help will really appreciated.
Thanks

**Comment by afshar-mohammad** [comment]
I have the same issue. Can anyone just tell me where the problem is? Maybe I can fix it.

In Chrome:

```
This page isn’t working
nl.gonewvm.com didn’t send any data.
ERR_EMPTY_RESPONSE
```

```
APJP.HTTP11.HTTPMessageException: HTTP_REQUEST_MESSAGE/READ
        at APJP.HTTP11.HTTPRequestMessage.read(HTTPRequestMessage.java:97)
        at APJP.HTTPS.HTTPSServerWorker.process(HTTPSServerWorker.java:234)
        at APJP.HTTPS.HTTPSServerWorker.run(HTTPSServerWorker.java:129)
        at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificat
e_unknown
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source
)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at java.io.InputStream.read(Unknown Source)
        at APJP.HTTP11.HTTPRequestMessage.read(HTTPRequestMessage.java:44)
        ... 3 more
```
